### PR TITLE
Sliders

### PR DESCRIPTION
**Pull request by AshutoshM29**
I have raised a PR for the "Slider Components", please provide reviews :)

Preview Link: https://deploy-preview-18--clean-ui-slider.netlify.app/pages/sliders/sliders

https://user-images.githubusercontent.com/89376505/159501275-54d8fb32-ecda-4295-bacd-65425dd6cc88.mp4

### CODE REVIEW

**Review by Sahil25061999 — APPROVED** [review]
looks good no suggestion for now, nice use comments, can be merged.

**Comment by varun-Tad** [comment]
The code looks neat and good. go ahead and merge

**Comment by varun-Tad** [comment]
https://user-images.githubusercontent.com/89238790/160082369-c4332387-0e9c-4833-9343-995f88df360a.mov

**Comment by varun-Tad** [comment]
> Screen.Recording.2022-03-25.at.1.51.48.PM.mov

notice the iframes are not minimising with the rest of the website. Might pose a problem if you plan to make it responsive.Would suggest you change the width of iframes to 100%.You can refer the video above

**Pull request merged**
